apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.metadata.name }}
  labels:
    name: {{ .Values.frontend.metadata.app }}
  namespace: {{ .Values.frontend.metadata.namespace }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.container.port }}
      targetPort: 80
  selector:
    app: {{ .Values.frontend.metadata.app }}
