apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.metadata.name }}
  labels:
    app: {{ .Values.backend.metadata.app }}
  namespace: {{ .Values.frontend.metadata.namespace }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.backend.metadata.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.metadata.app }}
    spec:
      containers:
        - name: {{ .Values.backend.metadata.name }}
          image: {{ .Values.backend.container.image }}  
          ports:
            - containerPort: {{ .Values.backend.container.port }}
          env:
            - name: POSTGRES_USERNAME
              value: "{{ .Values.backend.env.POSTGRES_USERNAME }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.backend.env.POSTGRES_PASSWORD }}"
            - name: POSTGRES_HOST
              value: "{{ .Values.backend.env.POSTGRES_HOST }}"
            - name: POSTGRES_DATABASE
              value: "{{ .Values.backend.env.POSTGRES_DATABASE }}"
            